# Site settings
title: Aerialship
email: aerialship@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AerialShip PHP libraries for SAML and Symfony 2 bundle
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aerialship.com" # the base hostname & protocol for your site
twitter_username: aerialship
github_username:  aerialship

highlighter: rouge

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap

breadcrumbs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            category: "blog"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
